### ISSUE TITLE
Revising Problem Statement

### ISSUE THREAD

**Issue by eugenelim9** [autumn-info-442a/team-g#1]
Google Doc: https://docs.google.com/document/d/1NbkYUs6BQM30QDkybAKPgOw62n-frBkvJ-TmEoTX9jY/edit

**Comment by lmj0328** [comment]
**Amy's comment on HW 1 (Reference Purpose)** 
It's concise and sound, but it raises many phenomena that it doesn't actually end up focusing on. For example, it talks about the problem of making devices affordable, and it mentions scheduling being important, but it never really says why scheduling is important and why schedule visibility is important. It also doesn't say much about the difference between personal and shared schedules. The result is a problem statement that seems unfocused, a bit vague. In your revision, try to be as precise as possible about what information is missing and why that's important.

**Comment by lmj0328** [comment]
**_Why is keeping a schedule important?_**
Research has also shown that having routines and schedules can have far-reaching psychological benefits. Routines have the power to improve our sleep, reduce anxiety and boost our cognitive function, and can even have an impact on mental health problems such as depression and bipolar disorder. 

For many of us, the COVID-19 outbreak has led to a sudden change to the way we work. We’re working different hours, different jobs and a lot of people working from home for the first time, while caring for children and relatives. This means our usual routines have been upended and we’ve had to quickly get used to new day-to-day schedules. Particularly for parents, having a routine makes things a little easier.

(https://www.yahoo.com/news/the-psychology-behind-why-we-love-routines-and-schedules-050053932.html?guccounter=1&guce_referrer=aHR0cHM6Ly93d3cuZ29vZ2xlLmNvbS8&guce_referrer_sig=AQAAABljDaZgHf0M8xQCWKcwZyl0zT8CIL7QO1iSOpc03DDbJMGcNmOtS8HhSey-k0XbIEkMQVwmMHEvd5egSiFjIfud4v3L2Xx_koAioYEXGXRFbcoX_ZJx0aTjMuytjeKJlt7Lb2whBCD7s9I17RqhNDjSRXQxdDQIg9irPKrF-_wf#:~:text=Research%20has%20also%20shown%20that,as%20depression%20and%20bipolar%20disorder.)

**Comment by lmj0328** [comment]
**_Why is schedule visibility important?_**
A well laid out visual calendar is easy to look at and allows you to gleam information quickly and effectively.(https://www.bizstim.com/news/article/importance-of-visualization-and-color-in-scheduling)

**Comment by lmj0328** [comment]
**_Why is schedule important for children?_**
Studies have shown that schedules and routines influence many aspects of children’s development (emotional, cognitive, and social). Predictable schedules help young children feel secure, safe and comfortable. Schedules and routines actually help reduce behavior problems, such as tantrums and aggression. A well-°©‐planned schedule can encourage children to be more actively involved in their play. Be sure to include activities that allow children to make choices, activities that are individualized for children’s special interests and/or needs and a balance of the planned activities, including small vs. large groups, quiet times vs. active times,teacher directed vs. child directed and indoor vs. outdoor. Children who are more actively involved in play are less likely to misbehave!

http://childcarerrnc.org/secrets/folder/030303/RoutinesandClassroomSchedules120907828.pdf
